name: Artifact Example - Incomplete Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Step
        id: build
        run: |
          echo "This is the build output." > build_output.txt

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Use Build Output
        run: |
            cat build_output.txt
